#dirName: Blogs
#dirPath: /users/ppuser/


# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
  password: adminadmin
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:mysql://localhost:3306/testdb